#!/bin/bash

_REPO_DIR_="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CALL_ORIGIN="$( pwd )"

source $_REPO_DIR_/scripts/initialize.sh
source $_REPO_DIR_/scripts/preprocessor.sh
source $_REPO_DIR_/scripts/handler_docker.sh
source $_REPO_DIR_/scripts/cmd.sh
source $_REPO_DIR_/conf

check_dir $REPO_DIR_NAME

if [ $? != 0 ] ; then echo "Terminating...NOW" >&2 ; exit 1 ; fi

# replace long arguments
args=( )
str=''
count=0
for arg; do
    if [[ $count -eq 0 ]];then
         str=''
        case "$arg" in
            build)      args+=( -D ); count=1;;
            exec)       args+=( -e ); count=-1;;
            init)       args+=( -i ) ;;
            preprocess) args+=( -p ); count=2;;
            test)       args+=( -t );;
            --help | help)     args+=( -h ) ;;
            *)          args+=( "$arg" ) ;;
        esac
    else
        str=$str" "$arg
        count=$(($count - 1))
        if [[ $count -eq 0 ]];then args+=( "$str" ); fi
    fi
done
if [[ $count -lt 0 ]];then args+=( "$str" ); fi


set -- "${args[@]}"

while getopts :D:e:hip:st OPTION; do
    : "$OPTION" "$OPTARG"
    case $OPTION in
        D)  docker_build $OPTARG; exit 0;;
        e)  dev_run $OPTARG;;
        h)  echo "usage"; exit 0;;
        i)  init $CALL_ORIGIN; exit 0;;
        p)  preprocess -c $OPTARG;;
        t)  dev_run -t, exit 0;;
        s)  echo "s";;
        \?) echo $OPTION"  "$OPTARG;;
    esac
done
