#!/bin/bash

_REPO_DIR_="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CALL_ORIGIN="$( pwd )"

source $_REPO_DIR_/scripts/initialize.sh
source $_REPO_DIR_/scripts/preprocessor.sh
source $_REPO_DIR_/scripts/cmd.sh
source $_REPO_DIR_/conf


if [ $? != 0 ] ; then echo "Terminating...NOW" >&2 ; exit 1 ; fi

# replace long arguments
args=( )
str=''
count=0
delim=''
for arg; do
    if [[ $count -eq 0 ]];then
        case "$arg" in
            exec)       args+=( -e ) count=-1; delim=''; str='';;
            init)       args+=( -i ) ;;
            preprocess) args+=( -p ); count=2; delim=''; str='';;
            test)       args+=( -t );;
            --help | help)     args+=( -h ) ;;
            *)          args+=( "$arg" ) ;;
        esac
    else
        str=$str$delim$arg
        delim=':'
        count=$(($count - 1))
        if [[ $count -eq 0 ]];then args+=( "$str" ); fi
    fi
done
if [[ $count -lt 0 ]];then args+=( "$str" ); fi


set -- "${args[@]}"

while getopts :hsip:e:t OPTION; do
    : "$OPTION" "$OPTARG"
    case $OPTION in
        e)  dev_run $OPTARG;;
        h)  echo "usage"; exit 0;;
        i)  init $CALL_ORIGIN; exit 0;;
        p)
            IFS=":" read config tmpl <<< "$OPTARG"
            preprocess -c $config $tmpl
        ;;
        t)  dev_run -t, exit 0;;
        s)  echo "s";;
        \?) echo $OPTION"  "$OPTARG;;
    esac
done
